version: '3.9'

services:
  balancer:
    image: 'jwilder/nginx-proxy'
    container_name: nginx-balancer
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: 'unless-stopped'  # Restart in case of failure
    networks:
        - app-network

  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    volumes:
      - ./.:/var/www/html
    hostname: ${APP_DOMAIN}
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=${APP_DOMAIN}
    user: "${UID:-1000}:${UID:-1000}"
    restart: 'unless-stopped'  # Restart in case of failure
    depends_on:
      - balancer
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: weather-redis
    ports:
      - "6379:6379"
    restart: 'unless-stopped'  # Restart in case of failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
